### ISSUE TITLE
Getting the following compiling issue - anything I'm doing wrong? 

### ISSUE THREAD

**Issue by adimehrotra** [REVrobotics/CANBridge#10]
compiling CANBridge.cpp failed.
In file included from /Users/andromeda/Downloads/scout-master/CANBridge/src/main/native/cpp/CANBridge.cpp:46:
/Users/andromeda/Downloads/scout-master/CANBridge/src/main/native/include/rev/Drivers/SerialPort/SerialDriver.h:44:25: error: 'GetName' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual std::string GetName() const {return "Legacy";}
                        ^
/Users/andromeda/Downloads/scout-master/CANBridge/src/main/native/include/rev/CANDriver.h:51:25: note: overridden virtual function is here
    virtual std::string GetName() const = 0;
                        ^
1 error generated.

**Comment by willtoth** [comment]
What environment are you using and how are you invoking the build?

Removing -Werror will fix this

**Comment by bumblebeerobotics** [comment]
Got it working! I just imported the project wrong :)
